CREATE SCHEMA IF NOT EXISTS "raw_spacex";
CREATE TABLE IF NOT EXISTS "raw_spacex"."launches" (
  "fairings" json,
  "links" json,
  "static_fire_date_utc" text,
  "static_fire_date_unix" integer,
  "tdb" boolean,
  "net" boolean NOT NULL,
  "window" integer,
  "rocket" text NOT NULL,
  "success" boolean,
  "failures" json,
  "details" text,
  "ships" text[],
  "capsules" json,
  "payloads" json,
  "launchpad" text NOT NULL,
  "auto_update" boolean NOT NULL,
  "flight_number" integer NOT NULL,
  "name" text NOT NULL,
  "date_utc" text NOT NULL,
  "date_unix" integer NOT NULL,
  "date_local" text NOT NULL,
  "date_precision" text NOT NULL,
  "upcoming" boolean NOT NULL,
  "tbd" boolean NOT NULL,
  "launch_library_id" text,
  "id" text NOT NULL,
  CONSTRAINT "launches_pkey" PRIMARY KEY ("id")
);
